config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions

  resources :campaigns do
    resources :emails
    member do
      get :welcome_message, defaults: { format: 'json' }
      get :unsubscribe_message, defaults: { format: 'json' }
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :subscriptions
  has_many :emails
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :campaign
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :campaign
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: %i[ show edit update destroy welcome_message unsubscribe_message ]

  # GET /campaigns or /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1 or /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns or /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to campaign_url(@campaign), notice: "Campaign was successfully created." }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1 or /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to campaign_url(@campaign), notice: "Campaign was successfully updated." }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1 or /campaigns/1.json
  def destroy
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: "Campaign was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campaign_params
      params.require(:campaign).permit(:name, :welcome_message, :unsubscribe_message)
    end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :set_campaign
  before_action :set_email, only: %i[ show edit update destroy ]

  # GET /emails or /emails.json
  def index
    @emails = Email.all
  end

  # GET /emails/1 or /emails/1.json
  def show
  end

  # GET /emails/new
  def new
    @email = Email.new
  end

  # GET /emails/1/edit
  def edit
  end

  # POST /emails or /emails.json
  def create
    @email = Email.new(email_params)

    respond_to do |format|
      if @email.save
        format.html { redirect_to campaign_email_url(@campaign, @email), notice: "Email was successfully created." }
        format.json { render :show, status: :created, location: [@campaign, @email] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emails/1 or /emails/1.json
  def update
    respond_to do |format|
      if @email.update(email_params)
        format.html { redirect_to campaign_email_url(@campaign, @email), notice: "Email was successfully updated." }
        format.json { render :show, status: :ok, location: [@campaign, @email] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emails/1 or /emails/1.json
  def destroy
    @email.destroy

    respond_to do |format|
      format.html { redirect_to campaign_emails_url(@campaign), notice: "Email was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_email
    @email = Email.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def email_params
    params.require(:email).permit(:name, :body, :order)
  end

  def set_campaign
    @campaign = Campaign.find(params[:campaign_id])
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: %i[ show edit update destroy ]

  # GET /subscriptions or /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1 or /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
    @campaigns = Campaign.all
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions or /subscriptions.json
  def create
    @campaigns = Campaign.find(params[:subscription][:campaign_id])
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save

        payload = { "SubscriptionID": @subscription.id.to_s,
                    "CampaignID": @subscription.campaign_id.to_s,
                    "EmailAddress": @subscription.email }

        client = Temporalio::Client.new(Temporal.connection, 'default')

        client.start_workflow(
          'UserSubscriptionWorkflow',
          payload,
          id: "email_drip_#{@subscription.id}",
          task_queue: Temporal.task_queue_name
        )

        format.html { redirect_to subscription_url(@subscription), notice: "Subscription was successfully created." }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1 or /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to subscription_url(@subscription), notice: "Subscription was successfully updated." }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
    client = Temporalio::Client.new(Temporal.connection, 'default')
    workflow = client.workflow_handle("email_drip_#{@subscription.id}")
    workflow.cancel("unsubscribed")

    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: "Subscription was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:email, :campaign_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/campaigns/_campaign.html.erb
<div id="<%= dom_id campaign %>">
  <p>
    <strong>Name:</strong>
    <%= campaign.name %>
  </p>

</div>

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign) do |form| %>
  <% if campaign.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
        <% campaign.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :welcome_message, style: "display: block" %>
    <%= form.text_area :welcome_message %>
  </div>

  <div>
    <%= form.label :unsubscribe_message, style: "display: block" %>
    <%= form.text_area :unsubscribe_message %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing campaign</h1>

<%= render "form", campaign: @campaign %>

<br>

<div>
  <%= link_to "Show this campaign", @campaign %> |
  <%= link_to "Back to campaigns", campaigns_path %>
</div>

app/views/campaigns/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Campaigns</h1>

<div id="campaigns">
  <% @campaigns.each do |campaign| %>
    <%= render campaign %>
    <p>
      <%= link_to "Show this campaign", campaign %>
    </p>
  <% end %>
</div>

<%= link_to "New campaign", new_campaign_path %>

app/views/campaigns/new.html.erb
<h1>New campaign</h1>

<%= render "form", campaign: @campaign %>

<br>

<div>
  <%= link_to "Back to campaigns", campaigns_path %>
</div>

app/views/campaigns/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @campaign %>

<div>
  <%= link_to "Edit this campaign", edit_campaign_path(@campaign) %> |
  <%= link_to "Show this campaign's emails", campaign_emails_path(@campaign) %> |
  <%= link_to "Back to campaigns", campaigns_path %>

  <%= button_to "Destroy this campaign", @campaign, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmailDripPolyglotRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription) do |form| %>
  <% if subscription.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <% if @subscription.new_record? %>
    <div>
      <%= form.label :campaign_id, "Campaign", style: "display: block" %>
      <%= form.collection_select(:campaign_id, Campaign.all, :id, :name) %>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<div id="<%= dom_id subscription %>">
  <p>
    <strong>Email:</strong>
    <%= subscription.email %>
  </p>

  <p>
    <strong>Campaign:</strong>
    <%= subscription.campaign_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= subscription.status %>
  </p>

</div>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to "Show this subscription", @subscription %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/subscriptions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Subscriptions</h1>

<div id="subscriptions">
  <% @subscriptions.each do |subscription| %>
    <%= render subscription %>
    <p>
      <%= link_to "Show this subscription", subscription %>
    </p>
  <% end %>
</div>

<%= link_to "New subscription", new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/subscriptions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subscription %>

<div>
  <%= link_to "Edit this subscription", edit_subscription_path(@subscription) %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>

  <%= button_to "Destroy this subscription", @subscription, method: :delete %>
</div>